baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Mood"
disableKinds = ["section"]
pygmentsCodeFences = false
pygmentsUseClasses = false
theme = "mood"

[minify]
  minifyOutput = true

[permalinks]
  post = ":slug/"

[params]
  description = "A moodboard of graphic inspiration."
  keywords = "Harry Cresswell, mood, moodboard, design inspiration"
  cloudinary_url = "https://res.cloudinary.com/harrycresswell/image/upload/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 5
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 10